services:
  web-app:
    container_name: shouter-web-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # separate db url due to docker networking (host=database)
      - DATABASE_URL=postgresql://postgres:password@database:5432/shouter
    depends_on:
      - database
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - shouter_network
    profiles:
      - dev

  database:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shouter
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - shouter_data:/var/lib/postgresql/data
    networks:
      - shouter_network
    profiles:
      - dev

  shouter-prod:
    container_name: shouter-web-app
    image: ghcr.io/borgaar/shouter:latest
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c 'prisma migrate deploy && node server.js'
    expose:
      - 3000
    ports:
      - 4000:3000
    networks:
      - shouter_network
    restart: unless-stopped
    profiles:
      - production

networks:
  shouter_network:
    driver: bridge
volumes:
  shouter_data:
    driver: local
