services:
  web-app:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - shouter_network

networks:
  shouter_network:
    external: true
